=== spohie001/snails-web-page-2020/strona_projekt_XML_Schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

<xs:element name="content">
    <xs:complexType >
			<xs:sequence>
                <xs:element name="informacje" type="informacjeType"/>
                <xs:element name="links" type="linksType"/>
            </xs:sequence>
    </xs:complexType >
</xs:element>

<xs:complexType name="informacjeType">
	<xs:sequence>
        <xs:element name="temat" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="linksType">
		<xs:sequence>
			<xs:element name="link" type="linkType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

    <xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
			 <xs:attribute name="source" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== spohie001/snails-web-page-2020/strona_projekt_XML.xml
<?xml version="1.0" encoding="utf-8"?>
<content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="strona_projekt_XML_Schema.xsd">
    <informacje>
        <temat>ogolne</temat>
        <temat>ksztalt</temat>
        <temat>roznorodnosc</temat>
        <temat>muszle</temat>
    </informacje>

    <links>
        <link source="https://en.wikipedia.org/wiki/Sea_snail#Anatomy">Wikipedia</link>
        <link source="https://ciekawe.org/2016/06/14/niezwykle-morskie-slimaki">ciekawe.org</link>
        <link source="https://wideo.wp.pl/maly-smok-niezwykle-morskie-slimaki-6510040777369729v">wideo.wp.pl</link>
    </links>

</content>
